### ISSUE TITLE
Bad lib path in install script

### ISSUE THREAD

**Issue by Marv-CZ** [CESNET/libnetconf2-cpp#2]
Please fix line

install(TARGETS netconf2-cpp DESTINATION lib)

to

install(TARGETS netconf2-cpp DESTINATION ${CMAKE_INSTALL_LIBDIR})

in CMakeList.txt to install the library to a correct folder.

**Comment by jktjkt** [comment]
Thanks! The patch turns out to be even simpler, can you please give it a try?

https://gerrit.cesnet.cz/c/CzechLight/libnetconf2-cpp/+/5912

**Comment by Marv-CZ** [comment]
Now it appears to be OK. Thanks!
