### ISSUE TITLE
No build possible for latest version of these bindings.

### ISSUE THREAD

**Issue by safesintesi** [CESNET/libnetconf2-cpp#3]
The CMake requirements on the latest commit on the master branch state as follow:
`pkg_check_modules(LIBNETCONF2 REQUIRED libnetconf2>=2.1.40 libnetconf2<3 IMPORTED_TARGET)`

In libnetconf2 though there only exist the `v2.1.37` (too low) and `v3.0.8` (too high) tags.
I notice that this is to prevent breaking changes from v3 as mentioned in https://github.com/CESNET/libnetconf2-cpp/commit/b266c534db8ec0c919fa685247411866274f26e7 , but at the same time there is no older tag we can use.

Would you suggest choosing a specific commit with a compatible version of libnetconf2 or pick an older bindings that can be compatible with older libnetconf2 tags? Can we use versions not part of the releases and consider them sufficiently stable?

Also, it would be great in next iterations for the required version to be stated directly in the README.md

**Comment by jktjkt** [comment]
Sorry for this. TL;DR: you need CESNET/libnetconf2@99fd7ad .

There's no tag/branch upstream for this latest-version-prior-to-a-major-update, and our CI cannot pin a project to a sha1 directly, so we have an internal branch that's listed from this project's `.zuul.yaml`, and that branch is only visible through our Gerrit.

I also agree that the docs are needed as well. Do you feel like contributing a README similar to what we have in libyang-cpp/sysrepo-cpp?

**Comment by safesintesi** [comment]
Thank you for the fast reply, seems to work.

For the README.md, I might take a look at it at soon I've some time. Can it be a pull request, or does it must go through gerrit?

**Comment by jktjkt** [comment]
yeah, upload that through Gerrit please

**Comment by safesintesi** [comment]
So, this morning I was bored and tried to write a quick README.md.  
Apparently my github account has no permissions on [https://gerrit.cesnet.cz](https://gerrit.cesnet.cz), and my university doesn't recognize it for any form of authentication so I can't push anything on there.
I can still do a quick pull request though, since it's just the readme.

**Comment by safesintesi** [comment]
If you instead need a patch file so you can add it through gerrit, here it is.
( It's a .txt instead of a .patch to workaround github limitations of file formats upload guidelines. )
[newReadMe.txt](https://github.com/CESNET/libnetconf2-cpp/files/14050981/newReadMe.txt)

**Comment by jktjkt** [comment]
libyang-v3 is now fully supported in today's master.
